### ISSUE TITLE
Several second delay when run with debugger on iPad

### ISSUE THREAD

**Issue by blwinters** [podkovyrin/APNumberPad#11]
I've been using APNumberPad in my project for a few months and it's generally great. However, I noticed that the first time I present my EditAmountViewController and load APNumberPad, there is a delay of about 10 seconds before the number pad appears. Subsequent instances of APNumberPad do not have a delay, until the app is run again. This problem only occurs when running the project on iPad.

Today, I downloaded the APNumberPad demo project and saw the same issue. I finally realized that this only occurs when running the project from Xcode with the debugger enabled. If I edit the Run scheme and deselect "Debug executable", the delay goes away. 

I'm guessing this is related to Auto Layout, but not sure. Please fix it if possible so that others don't face the same confusion I have for the past few months.

**Comment by podkovyrin** [comment]
Thanks! I'll take a look

**Comment by mommyme** [comment]
Was this ever solved?

**Comment by podkovyrin** [comment]
@mommyme I did investigation on this issue, but had no luck. So, this issue appears only in Debug configuration (on iPad) and it seems to be iOS bug with custom `inputView`s. APNumberPad itself didn't do any heavy layout (it even don't use AutoLayout) or something that may affect app performance.
