### ISSUE TITLE
Set keyboard width

### ISSUE THREAD

**Issue by Meonardo** [podkovyrin/APNumberPad#13]
Hi, I know this is not an issue. I m using APNumberPad in iPad App and I want to know how can I set the keyboard width, just like the appearance of "Setting" App in iPad-->Touch ID & Password.

**Comment by podkovyrin** [comment]
There is no built in way to do it. Feel free to fork and edit this behaviour:
[APNumberPad.m#L124](https://github.com/podkovyrin/APNumberPad/blob/master/APNumberPad/Classes/APNumberPad.m#L124)
[APNumberPad.m#L137](https://github.com/podkovyrin/APNumberPad/blob/master/APNumberPad/Classes/APNumberPad.m#L137)
