### ISSUE TITLE
iPhone X compatibility

### ISSUE THREAD

**Issue by ethanwa** [podkovyrin/APNumberPad#18]
Hi, anyone out there still working on this? We really need some iPhone X compatibility. The keyboard is too low on the screen and is in the safe area. Thank you!

**Comment by podkovyrin** [comment]
Let me check it

**Comment by ethanwa** [comment]
Thank you, I appreciate it. We've just added this as a new Pod to our project so our users can use an X button when entering in old 10-digit ISBN numbers from books. Very useful. Thank you for making this!

**Comment by ethanwa** [comment]
Works great on iPhone X! I'll check on a non-X device shortly to make sure it didn't break anything.

**Comment by ethanwa** [comment]
Looks good on iPhone SE as well

**Comment by podkovyrin** [comment]
Great! Thanks!
