### ISSUE TITLE
Minimum Support Version

### ISSUE THREAD

**Issue by DeftMKJ** [podkovyrin/APNumberPad#22]
The project introduces the version after iOS 9, why can't I run on iOS 8, is there any problem?
Can you give points that need to be adapted iOS 8?

**Comment by podkovyrin** [comment]
Good point, actually there shouldn't be any problems with iOS 8. I'll update it soon

**Comment by podkovyrin** [comment]
Give it a try: `pod 'APNumberPad', '1.2.3'`
