### ISSUE TITLE
Delegate is nil.

### ISSUE THREAD

**Issue by cukingpro** [podkovyrin/APNumberPad#24]
`class DecimalNumberPad: APNumberPad {

    convenience init() {
        self.init(delegate: DecimalNumberPadDelegate())
        leftFunctionButton.setTitle(".", for: .normal)
    }

}`

`class DecimalNumberPadDelegate: NSObject, APNumberPadDelegate {
    
    func numberPad(_ numberPad: APNumberPad, functionButtonAction functionButton: UIButton, textInput: UIResponder & UITextInput) {
        textInput.insertText(".")
    }

}`

When I create delegate class, the delegate is nil when I click on left button.

It doesn't happen when I set delegate is viewcontroller

**Comment by podkovyrin** [comment]
It happens because `delegate` is stored as weak:
https://github.com/podkovyrin/APNumberPad/blob/master/APNumberPad/Classes/APNumberPad.m#L36

You need to keep a strong reference to your `DecimalNumberPadDelegate` somewhere.

**Comment by nagurbee** [comment]
for me also it is not working can some one please help me
