### ISSUE TITLE
Suggestion: Use UIKeyInput instead of UITextInput

### ISSUE THREAD

**Issue by zackdotcomputer** [podkovyrin/APNumberPad#27]
Right now, the keyboard is taking on a lot of the logic of how the control should respond to a keypress. This isn't really the job of the keyboard - instead I think the keyboard should require conformance to `UIKeyInput` from the targeted view and just send it single key events using the `insertText` and `deleteBackward` methods.

**Comment by zackdotcomputer** [comment]
Oh interesting - I see you're already using those methods. I'm going to create a quick PR that loosens the type constraint for the inputView without losing the delegate functionality since I'm not sure how you're using it currently.

**Comment by podkovyrin** [comment]
`1.2.4` fixes the issue
