### ISSUE TITLE
Feature Request: Any chance you could make this work for iPad as well?

### ISSUE THREAD

**Issue by ethanwa** [podkovyrin/APNumberPad#31]
Looking for a numbers-only iPad keyboard with an additional letter (in my case X for ISBN numbers).

**Comment by podkovyrin** [comment]
I remember It was optimized for iPad. https://github.com/podkovyrin/APNumberPad/blob/master/APNumberPad/APNumberPad.m#L142
Though I guess the current implementation appearance might look outdated in the new iOS versions. 
Do you have any particular issues or it's just broken in the iPad now?

**Comment by ethanwa** [comment]
I stand corrected! It appears to be working, it was an error in my code. Apologies!
