### ISSUE TITLE
Xcode 12.5 Beta 3 SPM: target 'APNumberPad' has invalid header layout: umbrella header found

### ISSUE THREAD

**Issue by ethanwa** [podkovyrin/APNumberPad#33]
Getting the following build error (Swift Package Manager):

> target 'APNumberPad' has invalid header layout: umbrella header found at '~/Library/Developer/Xcode/DerivedData/collectors-cxrmmuolpcbfkpdnxggydzzxsvnh/SourcePackages/checkouts/APNumberPad/APNumberPad/APNumberPad.h', but directories exist next to it: ~/Library/Developer/Xcode/DerivedData/collectors-cxrmmuolpcbfkpdnxggydzzxsvnh/SourcePackages/checkouts/APNumberPad/APNumberPad/Assets, ~/Library/Developer/Xcode/DerivedData/collectors-cxrmmuolpcbfkpdnxggydzzxsvnh/SourcePackages/checkouts/APNumberPad/APNumberPad/Private; consider removing them

This error is new to Xcode 12.5. Everything works just fine in 12.4. The issue could be because of this change in 12.5:

> **Swift Packages
> New Features**
> The Swift Package Manager now builds package products and targets as dynamic frameworks automatically, if doing so avoids duplication of library code at runtime. (59931771) (FB7608638)
> 
> Swift packages that specify a 5.4 tools version can now explicitly declare targets as executable, which allows the use of the @main keyword in package code. (SE-0294, 47691185)
> 
> Swift Package Manager caches package dependencies on a per-user basis, which reduces the amount of network traffic and increases performance of dependency resolution for subsequent uses of the same package. If needed, you can disable cache use in xcodebuild by using the new -disablePackageRepositoryCache flag. (72204929)

**Comment by ethanwa** [comment]
Hoping for an update to this at some point...

**Comment by podkovyrin** [comment]
Sorry, was quite busy with other stuff. The issue has been fixed in #34

**Comment by ethanwa** [comment]
Thank you for taking the time to do this!! I really appreciate all the work you’ve put into this project.

**Comment by ghr1234** [comment]
Please close this issue.
